#!/usr/bin/env bash
# Garden Pi: serve the MagicDNS name on wlan0 so Chrome trusts the existing
# Let's Encrypt cert without Tailscale on the phone.
#
# Public CAs (including paid ones) will not sign 192.168.8.133. The cert we
# already have is valid — the kiosk just has to open the name on the cert.
#
# Run on the garden Pi:
#   sudo ./scripts/install-garden-lan-dns.sh
#
# Then point the kiosk at that name, and set the phone's Wi-Fi DNS to the Pi
# (or leave Tailscale always-on). See docs/garden.md.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# Garden Pi already runs stock dnsmasq on wlan0:53. Drop a snippet into
# /etc/dnsmasq.d instead of a second daemon fighting for the port.
CONF=/etc/dnsmasq.d/hue-garden-tls.conf
DEFAULT_HOST=kolonihave-pi.tail7947c4.ts.net

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo $0" >&2
  exit 1
fi

HOST=""
if [[ -f "$ROOT/certs/public-url.txt" ]]; then
  HOST="$(sed -E 's#https://([^:/]+).*#\1#' "$ROOT/certs/public-url.txt" | tr -d '\r')"
fi
HOST="${TS_CERT_HOSTNAME:-$HOST}"
HOST="${HOST:-$DEFAULT_HOST}"

IFACE="${HUE_LAN_IFACE:-wlan0}"
LAN_IP="$(ip -4 -o addr show dev "$IFACE" 2>/dev/null | awk '{print $4}' | cut -d/ -f1 | head -n1 || true)"
if [[ -z "$LAN_IP" ]]; then
  echo "No IPv4 on $IFACE. Connect garden Wi-Fi first." >&2
  exit 1
fi

if ! command -v dnsmasq >/dev/null 2>&1; then
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq dnsmasq
fi

cat > "$CONF" <<EOF
# Generated by install-garden-lan-dns.sh — do not edit.
listen-address=${LAN_IP}
bind-interfaces
domain-needed
bogus-priv
no-resolv
server=1.1.1.1
server=8.8.8.8
address=/${HOST}/${LAN_IP}
EOF
chmod 644 "$CONF"

systemctl enable dnsmasq 2>/dev/null || true
systemctl restart dnsmasq

echo "✓ ${HOST} → ${LAN_IP} on ${IFACE}:53"
echo
echo "On the garden kiosk Wi-Fi: DNS = ${LAN_IP} (not the router)."
echo "Kiosk URL: https://${HOST}:8443"
echo "Do not open https://${LAN_IP}:8443 — Chrome fetch() will still fail the cert."
